apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
  namespace: traefik

spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service
  namespace: traefik

# spec:
#   type: LoadBalancer
#   ports:
#     - targetPort: web
#       port: 80
#   selector:
#     app: traefik
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000 # Optional; Kubernetes will assign a port if not specified
  selector:
    app: traefik


